print("Please fill in the blanks below:")
print("______(name)______'s favorite subject in school is ______(subject)________.")
name = input("What is name? ")
subject = input("What is subject? ")
print(f"{name} 's favorite subject in school is {subject}.")